name: Build Flutter APK dari ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract ZIP
        run: |
          mkdir project
          unzip project.zip -d project

          echo "Isi folder:"
          find project -maxdepth 3 -type f | head -50

      - name: Cari pubspec.yaml
        run: |
          PROJECT_DIR=$(find project -name pubspec.yaml -print -quit | xargs dirname)

          if [ -z "$PROJECT_DIR" ]; then
            echo "pubspec.yaml tidak ditemukan"
            exit 1
          fi

          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Pub Get
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter pub get

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
